from kytool.domain.exceptions import InternalException


class AssigmentException(InternalException):
    pass
